## local, dev 공통
### 메일
#TODO: 계정 비밀번호 지우기
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: giftrio.contact@gmail.com
    password: uqaqqtkwskgxvljl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

---

spring:
  profiles:
    active:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/h2/giftrio
    username: sa
    password: '1234'
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: create

---

spring:
  profiles:
    active:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/giftrio_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    password: '1234'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  config:
    activate:
      on-profile: dev
